sudo: required
services:
  - docker

before_install:
  - docker build -t stevensymons/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevensymons/docker-react npm run test -- --coverage
