sudo: required
services:
  - docker

before_install:
  - docker build -t stevensymons/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevensymons/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "awssucks"
  env: "awssucks-env"
  bucket_name: elasticbeanstalk-eu-west-2-766106480256
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
